// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzrrsjkitgrkuhcbkzxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6cnJzamtpdGdya3VoY2JrenhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTg4ODAsImV4cCI6MjA2MjEzNDg4MH0.ec-4ukySE9CA7kkYujnD2kBpffJhToLKeYVJJBddDJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);